### ISSUE TITLE
Improve the CLI UX for dbt project

### ISSUE THREAD

**Issue by popcornylu** [InfuseAI/piperider#578]
# Introduction
The main use case is to integrate PipeRider with dbt project. This goal of this story is even to improve the CLI UX when using piperider in the dbt project use case.

Here are the feature list

1. Implicit data sources from dbt profile/target
1. `piperider run` would profile all table models in dbt project (rather than tables in the data source)
1. Allows to annotate a model as candidate for piperider
1. Use dbt list to select model for piperider

# Features
## Implicit data sources from dbt profile/target

Here is the dbt profile.yml
```
# profile.yml
infusetude:
  target: dev
  outputs:
    dev:
      type: snowflake
      ...
      schema:
      threads: 4
    prod:
      type: snowflake
      ...
      schema:
      threads: 4
```

The new generated config by `piperider init` would be like this one

```
dataSources: []
dbt:
   projectDir: .
```

The `dbt` attribute indicates that it is a dbt project, and the implicit data sources `dev` and `prod` would be available in the `piperider run`

It makes the `profiles.yml` be the single source of truth to connect to your data warehouse.

## piperider run would profile all models in dbt project

For a dbt project, the original behavior is 

- `piperider run`: profile all tables in the data source
- `piperider run --dbt-state target/`: profile all models in the target/run_results.json`

The problem is that it does not allow adhoc profiling without another `dbt run` or `dbt build`

The new behavior is

- `piperider run`: profile all table models in the dbt project (rather than tables in the data source's database+schema)
- `piperider run --dbt-state /tmp/prod`: profile all table models in the `/tmp/prod/manifest.json`, which is generated by `dbt run --target-path /tmp/prod`. See [dbt manifest](https://docs.getdbt.com/reference/artifacts/manifest-json)
- `piperider run --dbt-run-results`: profile all table models run in the latest dbt run. It also integrate the dbt test results.

## Allows to annotate a model as piperider candidate

Profiling is expensive. It is recommended to whitelist the models which is allowed to do the profiling. We use [dbt tags](https://docs.getdbt.com/reference/resource-configs/tags) to mark a model as `piperider`

To enable this feature, you need to edit the `.piperider/config.yml` with `dbt.tag`

```yaml
dataSources: []
dbt:
   projectDir: .
   tag: piperider
```

and then mark your model with piperider tag

```yaml
# models/myconfig.yml

version: 2

models:
  - name: model_name
    config:
      tags: [piperider]

    columns:
      - name: column_name
         ...
```

Remember to regenerate the [manifests.json](https://docs.getdbt.com/reference/artifacts/manifest-json) and run piperider

```shell
# update the manifest.json
dbt compile
# run again
piperider run
```

## Use dbt list to select model for piperider

For adhoc profiling/exploration case, it is useful to select models/metrics to query. PipeRider leverage the `dbt list` command to select models/metrics.

```
dbt list -s models/mymodel.sql | piperider run --dbt-list
```

# Breaking Changes

For dbt project, the command behavior changes

Old | New
--------|----------
`piperider run` | no equivalent. Or you should manually configure a non-dbt data source to do the profiling
`piperider run --dbt-state target/` | `piperider run --dbt-state target/ --dbt-run-results`

sc-30406
