### ISSUE TITLE
New PipeRider compare command

### ISSUE THREAD

**Issue by popcornylu** [InfuseAI/piperider#591]
# Introduction

To code review the model change, we would like to compare the profiling and metric queries between PR branch and main branch. However, there are many steps for the whole process

1. Switch branch between pr branch and main branch
2. Run dbt for the two branches
3. Run piperider for the two branches

In order to make the process well-defined and reproducible, we would like to source control the workflow for pr comparison somewhere and use single unified command to run the workflow. Here is the `piperider compare` command comes in

# Requirements
1. The default behavior of `piperider compare` is to compare current branch with main branch. 
2. Allows to define other RECIPEs to do the compare. (e.g. the branch to switch, the dbt commands to run)
3. Use `piperider compare --recipe <recipe>` to change the comparison workflow

# Default Compare Recipe

The default recipe is generated when run the `piperider init`
```yaml
# .piperider/compare/default.yml
base:
  branch: main
  dbt:
    commands:
    - dbt deps
    - dbt build
  piperider:
    command: piperider run
target:
  dbt:
    commands:
    - dbt deps
    - dbt build
  piperider:
    command: piperider run
```

and then run
```
piperider compare
```

You can change the default recipe later on. Just use editor to modify the configuration at `.piperider/compare/default.yml`

# Custom Compare Recipe
 Create a new file at `.piperider/compare/<recipe>.yml` and use `piperider compare --recipe <recipe>` to run this recipe

# Example recipes

## Dev recipe (since v0.20.0)
This is a process to do the run and compare with the same base report. The requirements are

1. The base result is from file
2. No dbt command run in target. We assume that we run the dbt command separately

```
# .piperider/compare/dev.yml
base:
  file: 'path/to/base/run.json'
target:
  piperider:
    command: 'piperider run'
```

## Slim CI recipe
[Slim CI](https://docs.getdbt.com/docs/deploy/cloud-ci-job#configuring-a-slim-ci-job) is a technique that we only transform the new and changed models comparing to the base state. Here are the requirement

1. We have already had production dbt state somewhere
2. Run PR branch dbt command with slim ci options
3. Run piperider with `--dbt-run-results` so that it only profile the models which is run in the latest dbt run

```
# .piperider/compare/slim-ci.yml
base:
  branch: main
  piperider:
    command: "piperider run --dbt-state path/to/prod/artifacts"
target:
  dbt:
    commands:
    - dbt deps
    - "dbt build --select state:changed+ --defer --state path/to/prod/artifacts"
  piperider:
    command: "piperider run --dbt-run-results"
```
