### ISSUE TITLE
`ValueError: Invalid isoformat string` error when running `piperider compare-reports` against a metric

### ISSUE THREAD

**Issue by waligob** [InfuseAI/piperider#676]
**Describe the bug**
Running `piperider compare-reports --last` against a dbt metric results in an error like `ValueError: Invalid isoformat string: '2023-04-01 00:00:00'`

**To Reproduce**
1. Setup new virtual environment and run pip install "piperider[bigquery]==0.23.3"
2. Initialize Piperider with `piperider init`
3. Add the `piperider` tag to a metric configuration file
4. Run `piperider run` twice to generate two reports
5. Run `piperider compare-reports --last --debug`
6. See an error like `ValueError: Invalid isoformat string: '2023-04-01 00:00:00'`

**Expected behavior**
The `compare-reports` command should create an HTML report and a Markdown report in the `.piperider/comparisons/` directory

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux
 - Python Version 3.9.16
 - Version: dbt 1.4.5, dbt metrics 1.4.0, piperider[bigquery]==0.23.3

**Additional context**

The offending metric configuration can be found below:

```yml
version: 2
metrics:
  - name: total_seconds_engaged
    label: Total Seconds Engaged
    model: ref('fct_hits')
    description: "The number of seconds readers spent viewing a page"
    calculation_method: sum
    expression: seconds_engaged
    timestamp: date
    time_grains: [day, week, month, quarter, year, all_time]
    dimensions:
      - article_arc_id
    tags:
      - piperider
```

The full output of `piperider compare-reports --last --debug` is attached:

[piperider_debug.txt](https://github.com/InfuseAI/piperider/files/11368215/piperider_debug.txt)
